version: '3.8'

services:
  web_service:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    ports:
      - '8000:8001'
    env_file: env/.env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - postgres

      #      - mongodb


  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: env/.env






  #  mongodb:
  #    image: mongo:latest
  #    ports:
  #      - '27017:27017'
  #    environment:
  #      MONGO_INITDB_ROOT_USERNAME: root
  #      MONGO_INITDB_ROOT_PASSWORD: rootpassword
  #    volumes:
  #      - mongodb_data:/data/db



volumes:
  media_volume:
  static_volume:
  postgres_data:


