# Generated by Django 4.2.8 on 2023-12-15 16:31

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cities",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(choices=[("region", "region"), ("district", "district")], max_length=255)),
                ("stocks", models.IntegerField(default=0)),
                ("tonnes", models.IntegerField()),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="apps.cities",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Stocks",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "cities",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cities", to="apps.cities"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fruits",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("weight", models.IntegerField()),
                (
                    "stocks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stocks", to="apps.stocks"
                    ),
                ),
            ],
        ),
    ]
